name: Build and Release Plugin

on:
  push:
    tags:
      - 'v*.*.*'
      
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}

          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Update version.txt
        run: echo "${{ steps.version.outputs.VERSION }}" > version.txt

      - name: Create plugin ZIP
        run: |
          zip -r mrf_translado_qgis.zip mrf_translado_qgis
            -x "*.git*" \
            -x "*__pycache__*" \
            -x "*.pyc" \
            -x "*.pyo" \
            -x "*.DS_Store" \
            -x "*.qrc"
            
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: MRF Translado GNSS ${{ steps.version.outputs.VERSION }}
          tag_name: ${{ steps.version.outputs.TAG }}
          files: mrf_translado_qgis.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install qgis-plugin-ci
        run: pip install qgis-plugin-ci

      - name: Publish plugin to QGIS
        run: |
          qgis-plugin-ci release ${{ steps.version.outputs.VERSION }} \
          --qgis-token ${{ secrets.QGIS_PLUGIN_TOKEN }}
