name: Build and Release Plugin

on:
  push:
    tags:
      - 'v*.*.*'
      
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Update version.txt
        run: echo "${{ steps.version.outputs.VERSION }}" > version.txt

      - name: Create plugin ZIP
        run: |
          zip -r mrf_translado_qgis.zip mrf_translado_qgis

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: MRF Translado GNSS ${{ steps.version.outputs.VERSION }}
          tag_name: ${{ steps.version.outputs.VERSION }}
          files: mrf_translado_qgis.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install qgis-plugin-ci
        run: pip install qgis-plugin-ci

      - name: Publish plugin to QGIS
        run: |
          qgis-plugin-ci release ${{ steps.version.outputs.VERSION }} \
          --qgis-token ${{ secrets.QGIS_PLUGIN_TOKEN }}
